// Generated by CoffeeScript 1.6.3
(function() {
  var controller, model, view, _base;

  controller = function(sb) {
    var destroy, init, model, update, view;
    model = null;
    view = null;
    init = function() {
      model = sb.getModel();
      model.subscribe(this);
      view = new sb.getView()(sb, model);
      return view.init();
    };
    destroy = function() {};
    update = function() {
      return sb.publish("cli", model.cmd);
    };
    return {
      init: init,
      destroy: destroy,
      update: update
    };
  };

  model = {
    cmd: "",
    enterPressed: false
  };

  view = function(sb, model) {
    var cli, init, onKeyUp;
    cli = null;
    onKeyUp = function(ev) {
      if (ev.which === '27') {
        model.cmd = '';
        return cli.val(model.cmd);
      } else {
        model.cmd = ($(this)).val();
        return model.enterPressed = ev.which === '13';
      }
    };
    model.notify();
    init = function() {
      cli = sb.tmpl("cli", {});
      cli.appendTo(sb.getContainer());
      cli.attr("placeholder", sb._("placeholder"));
      return cli.keyup(onKeyUp);
    };
    return {
      init: init
    };
  };

  if ((_base = swe.modules).cli == null) {
    _base.cli = {
      controller: controller,
      model: model,
      view: view
    };
  }

}).call(this);
